### ISSUE TITLE
Roadmap to 2.0.0-release

### ISSUE THREAD

**Issue by tngan** [tngan/samlify#65]
**Issues**

- [x] #50 Expose request ID and response ID for SPA (Another API break)
- [x] #66 Fix typo
- [x] #67 Fix the NameIDFormat replacement in redirect binding
- [x] #68 Handling extra query parameters in binding location
- [x] #69 Generic replacement of tags

**Documentation**

- [x] Review (including #70)

**Enhancements**

- [x] #64 Add trigger for signing entired message
- [x] #63 Options in signature construction

**Tests**

- [x] Coverage (#84)

### v2.0.1-rc.3 is released
